acciones_siniestro.php
siniestros.php

Se creo el formulario basico para registrar un siniestro, falta id_coche y que cargue los datos preterminados.

Se creo el modulo de "siniestros"

---

acciones_siniestro.php
siniestros.php

Se creo el formulario y la tabla de inventarios.

Creacion del modulo de Siniestros

---

acciones_documentacion.php
documentacion.php

Finalizacion del modulo DOCUMENTACION

Finalizacion del modulo DOCUMENTACION

---

acciones_documentacion.php
acciones_mantenimiento.php
acciones_prestamos.php
acciones_siniestro.php
autorizar_mantenimiento.php
autorizar_prestamo.php
documentacion.php
encabezado.php
mantenimiento.php
menu.php
prestamos.php
siniestros.php

Se termino el modulo, se aplicaron cambios de diseño y se pulieron procesos del resto de modulos como revision general del sistema.

Version Final AUTORIZA MANTENIMIENTO

---

AccionesCheckVehiculo.php
checkVehiculo.php

Se suben modificaciones del cheokin

Se suben modificaciones del cheokin

---

acciones_prestamos.php
autorizar_prestamo.php
prestamos.php

Se aplicaron los primeros cambios de la retroalimentacion de la directiva, solo se modificaron prestamos, autoriza prestamos y acciones prestamos.

Cambios modulo Prestamos

---

acciones_prestamos.php
prestamos.php

Se corrige insert de prestamos

Se corrige insert de prestamos

---

menu.php

Se agrega checkin en el menu

---

acciones_mantenimiento.php
acciones_siniestro.php
acciones_ver_doc.php
ver_documentacion.php

Se implento el modal para ver los detalles de siniestro

Modal "Siniestro"

---

acciones_documentacion.php
acciones_mantenimiento.php
acciones_siniestro.php
acciones_ver_registros.php
autorizar_mantenimiento.php
autorizar_prestamo.php
documentacion.php
mantenimiento.php
prestamos.php
seguimiento_documentacion.php
seguimiento_mantenimiento.php
seguimiento_siniestro.php
siniestros.php
ver_registros.php

Finalizacion de modulos de seguimiento

Finalizacion de modulos de seguimiento

---

AccionesCheckVehiculo.php

se agregan campos faltantes para el cheklsit de documentacion

se agregan campos faltantes para el cheklsit de documentacion

---

AccionesCheckVehiculo.php

se agrega 0000-00-00 vencimiento como parametro

se agrega 0000-00-00 vencimiento como parametro

---

AccionesCheckVehiculo.php

fecha vacia

---

AccionesCheckVehiculo.php

fecha null

---

checkVehiculo.php

Se quita validacion del formulario

Se quita validacion del formulario

---

acciones_kilometraje.php

correcion checkout

---

acciones_prestamos.php
menu.php

Se modifica icono del menu y se quita variable de acciones prestamo

Se modifica icono del menu y se quita variable de acciones prestamo

---

acciones_prestamos.php

se corrige query prestamos

---

AccionesCheckVehiculo.php
autorizar_prestamo.php

se ocultan campos en la vista de prestamos

se ocultan campos en la vista de prestamos

---

index.php

se quita correo de Sebas del login

se quita correo de Sebas del login

---

acciones_kilometraje.php
encabezado.php

subir mas de un archivo en checks

subir mas de un archivo en checks

---

acciones_prestamos.php
autorizar_prestamo.php

CORRECCION DOBLE CHEK

---

AccionesCheckVehiculo.php
autorizar_prestamo.php
checkVehiculo.php
encabezado.php
img/acciones_calendario.php
img/verActividades.php

Cambios en checkin/checkout y el checklist

Se aplican cambios diversos

---

img/acciones_calendario.php
img/verActividades.php

Actualizacion calendario planeadas

Actualizacion calendario planeadas

---

acciones_prestamos.php

se actualiza query de prestamos para area

se actualiza query de prestamos para area

---

acciones_prestamos.php

cambios en autoriza

---

img/acciones_calendario.php
img/verActividades.php

se aplican cambios de acuerdo a la nueva consulta

se aplican cambios de acuerdo a la nueva consulta

---

img/verActividades.php

Se actualiza catalogo de areas en el select

Se actualiza catalogo de areas en el select

---

acciones_kilometraje.php
acciones_prestamos.php
autorizar_prestamo.php
encabezado.php
img/acciones_calendario.php
menu.php

Actualizacion check para logistica, modificacion de queries del modulo de prestamos

Actualizacion check para logistica

---

acciones_kilometraje.php
acciones_prestamos.php
autorizar_prestamo.php
encabezado.php

Se valida chechout

---

.gitignore
acciones_mantenimiento.php
autorizar_mantenimiento.php
verActividades.php

SE AGREGA CAMPO COSTO Y SE MEJORA VISTA DE CALENDARIO DE PRESTAMOS

SE AGREGA CAMPO COSTO Y SE MEJORA VISTA DE CALENDARIO DE PRESTAMOS

---

autorizar_mantenimiento.php
prestamos.php

envia notificacion
